backend:
  name: github
  repo: rickthedev/drankSpellen

media_folder: "static/assets/"
public_folder: "assets"

collections:
  - name: Game
    label: game
    folder: src/games
    create: true
    fields:
      - { name: title, label: Titel, widget: string }
      - { name: players, label: Spelers, widget: string }
      - label: "Moeilijkheidsgraad"
        name: "difficulty"
        widget: "select"
        options:
          - { label: Makkelijk, value: makkelijk }
          - { label: Gemiddeld, value: gemiddeld }
          - { label: Moeilijk, value: moeilijk }
      - { name: short, label: Kort, widget: text }
      - { name: image, label: Afbeelding, widget: image }
      - { name: body, label: Omschrijving, widget: markdown }
